name: CI/CD — Build & Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore src/RajLaxmiElectrical.sln

      - name: Build
        run: dotnet build src/RajLaxmiElectrical.sln --no-restore --configuration Release

      - name: Run tests
        run: |
          # If you add tests, run them here
          echo "No tests configured yet"

      - name: Publish project
        run: dotnet publish src/RajLaxmiElectrical.Web/RajLaxmiElectrical.Web.csproj -c Release -o publish_output

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish_output